# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
#zh-Hans
# Site
title: 壹拾肆
subtitle: 闲言和碎语
description: "我独自一人/照顾着/历代的星辰"
author: Kaaaaai
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://kaaaaai.cn
root: /
permalink:  /articles/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - baidu_verify_OGUkScuBPi.html
  - google61da0cde098f3164.html
  - 404.html
  - BingSiteAuth.xml

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

image_stream:
  jquery: //cdn.bootcss.com/jquery/2.1.0/jquery.min.js
  jquery_lazyload: //cdn.bootcss.com/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  img_placeholder: https://ws4.sinaimg.cn/large/e724cbefgw1etyppy7bgwg2001001017.gif

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

#hexo sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# permalink: :title/
#permalink: archives/abbrlink.html
#abbrlink:
#  alg: crc32  # 算法：crc16(default) and crc32
#  rep: hex    # 进制：dec(default) and hex

# Extensions
## Plugins: https://hexo.io/plugins/
#RSS订阅
plugin: 
- hexo-generator-feed

live2d:
  model: hijiki
  bottom: -20


## Themes: https://hexo.io/themes/
theme: next-x

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#root@119.29.26.101:/home/edison/kclouds.git
#git@git.oschina.net:woailvkai/woailvkai.git
deploy:
  type: git
  repo: 
    github: git@github.com:Edison0620/Edison0620.github.io.git
    oschina: git@git.oschina.net:woailvkai/woailvkai.git
  branch: master